name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  mobstacker:
    aliases: ["stacker"]
    description: "Show stats about stacked mobs."